# Generated by Django 4.2.4 on 2023-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='state',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='South Africa', max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'Singel Cubic'), ('2', 'Group Cubic')], max_length=50),
        ),
    ]
