# Generated by Django 4.2.4 on 2023-09-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_state_hotels_province_alter_hotels_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unizulu Library', max_length=30)),
                ('floor', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('province', models.CharField(default='Kwazul-Natal', max_length=50)),
                ('country', models.CharField(default='South Africa', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='price',
        ),
        migrations.AddField(
            model_name='rooms',
            name='Course',
            field=models.CharField(default='Introductory Computing', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'Individual Cubicle'), ('2', 'Group Cubicle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.cubicle'),
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
