# Generated by Django 4.2.4 on 2023-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_cubicle_remove_rooms_price_rooms_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
