# Generated by Django 4.2.4 on 2023-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='roomnumber',
            field=models.CharField(max_length=30),
        ),
    ]
