# Generated by Django 4.2.4 on 2023-10-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rooms_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='user',
        ),
    ]
